.. comment - Obtaining the Server

`Download a Stackato VM <http://www.activestate.com/stackato/download_vm>`_
in the hypervisor format of your choice or
`get access <http://www.activestate.com/stackato/cloud_hosted>`_
to an image hosted on Amazon EC2 or HP Cloud Services.

Host system requirements:

* x86_64 processor with **VT-x enabled** (x86 virtualization).
* 3GB+ memory
* 3GB+ disk space

.. note::
  The Stackato VM uses 2GB of memory by default. Ensure that there is
  sufficient memory remaining on the host system to run the host
  operating system and any other applications you require. 

