
1. `Download the client <http://www.activestate.com/stackato/download_client>`_ for your platform (Windows, OS X, Linux x86, Linux x64)

2. Unzip the archive in a convenient directory.

3. Add the the executable to your system/shell $PATH by:

  * moving it to a directory in your $PATH,
  * creating a symlink from a directory in your $PATH, or
  * creating a shell alias for the executable.

4. Confirm that the client is installed correctly by running ``stackato -v`` or ``stackato help``.
