.. note::

  **Harbor (Port Service) Node Configuration**
  
  The optional :ref:`Harbor <harbor>` TCP/UDP port service must be set up
  on a node with a public network interface if you wish to enable port
  forwarding for user applications. The security group or firewall
  settings for this node should make the configured port range accessible
  publicly. See :ref:`Harbor Setup <harbor-setup>` for full configuration
  instructions.